# @package _group_

val:
  - _target_: sharpf.evaluation.RegressionEvaluator
    input_key: distances
    output_key: pred_distances

  - _target_: sharpf.evaluation.IllustratorDepths
    task: 'regression'
    golden_set_ids: {'/gpfs/gpfs0/3ddl/sharp_features/data_v2_cvpr/images/high_res.json/0.0/test/train_0.hdf5': [0, 1, 2]}
    k: 5

test:
  - _target_: sharpf.evaluation.RegressionEvaluator
    input_key: distances
    output_key: pred_distances

  - _target_: sharpf.evaluation.IllustratorDepths
    task: 'regression'
    golden_set_ids: {'/gpfs/gpfs0/3ddl/sharp_features/data_v2_cvpr/images/high_res.json/0.0/test/train_0.hdf5': [0, 1, 2]}
    k: 5