# @package _group_

val:
  - _target_: sharpf.evaluation.SegmentationEvaluator
    input_key: close_to_sharp_mask
    output_key: pred_mask

test:
  - _target_: sharpf.evaluation.SegmentationEvaluator
    input_key: close_to_sharp_mask
    output_key: pred_mask