# @package _group_

val:
  - _target_: sharpf.evaluation.RegressionEvaluator
    input_key: distances
    output_key: pred_distances

test:
  - _target_: sharpf.evaluation.RegressionEvaluator
    input_key: distances
    output_key: pred_distances