# @package _group_

val:
  - _target_: sharpf.evaluation.RegressionEvaluator
    input_key: distances
    output_key: pred_distances

test:
  - _target_: sharpf.evaluation.RegressionEvaluator
    input_key: distances
    output_key: pred_distances
  - _target_: sharpf.evaluation.IllustratorPoints
    golden_set_item_ids: ~
    k: 5