# @package _group_

val:
  - _target_: sharpf.evaluation.RegressionEvaluator
    input_key: distances
    output_key: distances

test:
  - _target_: sharpf.evaluation.RegressionEvaluator
    input_key: distances
    output_key: distances
    mask_expressions:
      - ['is_flat', '=', false]
      - ['has_sharp', '=', true]
      - ['has_smell_coarse_surfaces_by_num_faces', '=', false]
      - ['has_smell_deviating_resolution', '=', false]
      - ['has_smell_sharpness_discontinuities', '=', false]
      - ['has_smell_bad_face_sampling', '=', false]
      - ['has_smell_mismatching_surface_annotation', '=', false]
      - ['has_smell_coarse_surfaces_by_angles', '=', false]
    baseline_hist_dir_path: '/gpfs/gpfs0/3ddl/sharp_features/baseline-hists/baseline-pc'
  - _target_: sharpf.evaluation.IllustratorPoints
    golden_set_item_ids: ~
    k: 5
    filter_expressions:
      - ['is_flat', '=', false]
      - ['has_smell_coarse_surfaces_by_num_faces', '=', false]
      - ['has_smell_deviating_resolution', '=', false]
      - ['has_smell_sharpness_discontinuities', '=', false]
      - ['has_smell_bad_face_sampling', '=', false]
      - ['has_smell_mismatching_surface_annotation', '=', false]
      - ['has_smell_coarse_surfaces_by_angles', '=', false]