# @package _group_

resolution: 0.02

val:
  - _target_: sharpf.evaluation.SharpnessEvaluator
    calculate_rmse: true

test_se:
  - ${evaluators.se}

test_se_vis_save:
  - ${evaluators.se}
  - ${evaluators.vis}
  - _target_: sharpf.evaluation.PredictionsSaving
    filter_expressions: ${evaluators.vis.filter_expressions}

test_whole:
  - ${evaluators.se}
  - _target_: sharpf.evaluation.PredictionsSaving

se:
  _target_: sharpf.evaluation.SharpnessEvaluator
  write_metrics_to_disk: true
  calculate_rmse: true
  calculate_bad_points: true
  calculate_iou: true
  calculate_ba: true
  calculate_rmse_dl1: true
  calculate_bad_points_dl1: true
  resolution: ${evaluators.resolution}
  bp_ts_per_resolution: [1, 2, 4, 8, 16]
  mask_expressions:
    - ['is_flat', '=', false]
  reference_hist_dirs: ~
  #      - ['baseline', '/gpfs/gpfs0/3ddl/sharp_features/baseline-hists/baseline-image']

vis:
  _target_: sharpf.evaluation.IllustratorPoints
  #    reference_metrics_dirs:
  #      - ['baseline', '/trinity/home/r.rakhimov/sharp_features/outputs/2020-10-15/22-47-31/metrics']
  resolution: ${evaluators.resolution}
  bp_ts_per_resolution: [8, 16]
  #  golden_set_item_ids: ~
  k: 5
  filter_expressions:
    - ['is_flat', '=', false]
    - ['has_smell_coarse_surfaces_by_num_faces', '=', false]
    - ['has_smell_deviating_resolution', '=', false]
    - ['has_smell_sharpness_discontinuities', '=', false]
    - ['has_smell_bad_face_sampling', '=', false]
    - ['has_smell_mismatching_surface_annotation', '=', false]
    - ['has_smell_coarse_surfaces_by_angles', '=', false]