# @package _group_

high_res_quantile: 4.389

train: ${transform.test}

val: ${transform.test}

test:
  _target_: sharpf.utils.abc_utils.torch.CompositeTransform
  transforms:
    - _target_: sharpf.utils.abc_utils.torch.ToTensor
      keys:
        - image
        - distances
        - ${datasets.normals_name}
      type: torch.FloatTensor
    - _target_: sharpf.utils.abc_utils.torch.PreprocessDepth
      quantile: ${transform.high_res_quantile}
    - _target_: sharpf.utils.abc_utils.torch.RenameKeys
      old_keys: ['image']
      new_keys: ['points']
    - _target_: sharpf.utils.abc_utils.torch.Concatenate
      in_keys:
        - points
        - ${datasets.normals_name}
      dim: 0
      out_key: 'points'
    - _target_: sharpf.utils.abc_utils.torch.DeleteKeys
      keys:
        - ${datasets.normals_name}
    - _target_: sharpf.utils.abc_utils.torch.ComputeIsFlatProperty
