# @package _group_

train:
  _target_: sharpf.utils.abc_utils.torch.CompositeTransform
  transforms:
    - _target_: sharpf.utils.abc_utils.torch.TypeCast
    - _target_: sharpf.utils.abc_utils.torch.HighResQuantileNormalize
    - _target_: sharpf.utils.abc_utils.torch.Standardize

val:
  _target_: sharpf.utils.abc_utils.torch.CompositeTransform
  transforms:
    - _target_: sharpf.utils.abc_utils.torch.TypeCast
    - _target_: sharpf.utils.abc_utils.torch.HighResQuantileNormalize
    - _target_: sharpf.utils.abc_utils.torch.Standardize

test:
  _target_: sharpf.utils.abc_utils.torch.CompositeTransform
  transforms:
    - _target_: sharpf.utils.abc_utils.torch.TypeCast
    - _target_: sharpf.utils.abc_utils.torch.HighResQuantileNormalize
    - _target_: sharpf.utils.abc_utils.torch.Standardize
