# @package _group_

high_res_quantile: 4.389

train: ${transform.test}

val: ${transform.test}

test:
  _target_: defs.utils.abc_utils.torch.CompositeTransform
  transforms:
    - _target_: defs.utils.abc_utils.torch.ToTensor
      keys: ['image','distances']
      type: torch.FloatTensor
    - _target_: defs.utils.abc_utils.torch.PreprocessDepth
      quantile: ${transform.high_res_quantile}
    - _target_: defs.utils.abc_utils.torch.RenameKeys
      old_keys: ['image']
      new_keys: ['points']
    - _target_: defs.utils.abc_utils.torch.ComputeIsFlatProperty
    - _target_: defs.utils.abc_utils.torch.ComputeTargetSharp
      resolution: ${datasets.resolution_q}
