# @package _group_

high_res_quantile: 4.389

train:
  _target_: sharpf.utils.abc_utils.torch.CompositeTransform
  transforms:
    - _target_: sharpf.utils.abc_utils.torch.ToTensor
      keys: ['image','distances']
      type: torch.FloatTensor
    - _target_: sharpf.utils.abc_utils.torch.PreprocessDepth
      quantile: ${transform.high_res_quantile}
    - _target_: sharpf.utils.abc_utils.torch.RenameKeys
      old_keys: ['image']
      new_keys: ['points']

val: ${transform.train}

test: ${transform.train}
