# @package _group_

# use this transform for inference only

high_res_quantile: 5.331804347038269

train: ${transform.test}

val: ${transform.test}

test:
  _target_: defs.utils.abc_utils.torch.CompositeTransform
  transforms:
    - _target_: defs.utils.abc_utils.torch.ToTensor
      keys: [ 'image','distances' ]
      type: torch.FloatTensor
    - _target_: defs.utils.abc_utils.torch.PreprocessArbitraryDepth
      quantile: ${transform.high_res_quantile}
      patch_based: true
    - _target_: defs.utils.abc_utils.torch.RenameKeys
      old_keys: [ 'image' ]
      new_keys: [ 'points' ]
    - _target_: defs.utils.abc_utils.torch.ComputeIsFlatProperty
