# @package _group_

high_res_quantile: 7.4776

train: ${transform.test}

val: ${transform.test}

test:
  _target_: sharpf.utils.abc_utils.torch.CompositeTransform
  transforms:
    - _target_: sharpf.utils.abc_utils.torch.ToTensor
      keys: ['image', 'distances']
      type: torch.FloatTensor
    - _target_: sharpf.utils.abc_utils.torch.PreprocessDepth
      quantile: ${transform.high_res_quantile}
    - _target_: sharpf.utils.abc_utils.torch.ComputeCloseToSharpMask
    - _target_: sharpf.utils.abc_utils.torch.DeleteKeys
      keys: ['background_mask', 'distances']
    - _target_: sharpf.utils.abc_utils.torch.RenameKeys
      old_keys: ['image']
      new_keys: ['points']
