# @package _group_

train:
  _target_: sharpf.utils.abc_utils.torch.CompositeTransform
  transforms:
    - _target_: sharpf.utils.abc_utils.torch.ToTensor
      keys:
        - points
        - distances
        - ${datasets.normals_name}
      type: torch.FloatTensor
    - _target_: sharpf.utils.abc_utils.torch.Center
      keys: ['points']
      dim: 0
    - _target_: sharpf.utils.abc_utils.torch.NormalizeL2
      keys: ['points']
      dim: 1
    - _target_: sharpf.utils.abc_utils.torch.Random3DRotation
      keys:
        - points
        - ${datasets.normals_name}

val: ${transform.test}

test:
  _target_: sharpf.utils.abc_utils.torch.CompositeTransform
  transforms:
    - _target_: sharpf.utils.abc_utils.torch.ToTensor
      keys:
        - points
        - distances
        - ${datasets.normals_name}
      type: torch.FloatTensor
    - _target_: sharpf.utils.abc_utils.torch.Center
      keys: ['points']
      dim: 0
    - _target_: sharpf.utils.abc_utils.torch.NormalizeL2
      keys: ['points']
      dim: 1
    - _target_: sharpf.utils.abc_utils.torch.ComputeIsFlatProperty
