# @package _group_

train:
  _target_: defs.utils.abc_utils.torch.CompositeTransform
  transforms:
    - _target_: defs.utils.abc_utils.torch.ToTensor
      keys: ['points', 'distances', 'voronoi']
      type: torch.FloatTensor
    - _target_: defs.utils.abc_utils.torch.Center
      keys: ['points']
      dim: 0
    - _target_: defs.utils.abc_utils.torch.NormalizeByMaxL2
      keys: ['points']
      dim: 1
    - _target_: defs.utils.abc_utils.torch.Random3DRotation
      keys: ['points']
    - _target_: defs.utils.abc_utils.torch.Concatenate
      in_keys: ['points', 'voronoi']
      dim: 1
      out_key: 'points'
    - _target_: defs.utils.abc_utils.torch.DeleteKeys
      keys: ['voronoi']

val: ${transform.test}

test:
  _target_: defs.utils.abc_utils.torch.CompositeTransform
  transforms:
    - _target_: defs.utils.abc_utils.torch.ToTensor
      keys: ['points', 'distances', 'voronoi']
      type: torch.FloatTensor
    - _target_: defs.utils.abc_utils.torch.Center
      keys: ['points']
      dim: 0
    - _target_: defs.utils.abc_utils.torch.NormalizeByMaxL2
      keys: ['points']
      dim: 1
    - _target_: defs.utils.abc_utils.torch.Concatenate
      in_keys: ['points', 'voronoi']
      dim: 1
      out_key: 'points'
    - _target_: defs.utils.abc_utils.torch.DeleteKeys
      keys: ['voronoi']
    - _target_: defs.utils.abc_utils.torch.ComputeIsFlatProperty