# @package _group_

# ref implementation: https://github.com/WangYueFt/dgcnn/blob/master/tensorflow/sem_seg/model.py

in_channels: 3

example_input_array:
  _target_: torch.rand
  size:
    - 1
    - 4096
    - ${model.in_channels}

model_class:
  _target_: sharpf.modeling.DGCNNHist
  a: 0.0
  b: 1.0
  discretization: 240
  margin: 2
  encoder_blocks:
    - _target_: sharpf.modeling.PointOpBlock
      neighbours:
        _target_: sharpf.modeling.NeighbourKNN
        k: 30
      local_transform:
        _target_: sharpf.modeling.LocalDynamicGraph
      feature_extractor:
        _target_: sharpf.modeling.StackedConv
        channels:
          - ${mul:2,${model.in_channels}}
          - 64
          - 64
      aggregation:
        _target_: sharpf.modeling.AggregationMax
    - _target_: sharpf.modeling.PointOpBlock
      neighbours:
        _target_: sharpf.modeling.NeighbourKNN
        k: 30
      local_transform:
        _target_: sharpf.modeling.LocalDynamicGraph
      feature_extractor:
        _target_: sharpf.modeling.StackedConv
        channels: [128, 64, 64]
      aggregation:
        _target_: sharpf.modeling.AggregationMax
    - _target_: sharpf.modeling.PointOpBlock
      neighbours:
        _target_: sharpf.modeling.NeighbourKNN
        k: 30
      local_transform:
        _target_: sharpf.modeling.LocalDynamicGraph
      feature_extractor:
        _target_: sharpf.modeling.StackedConv
        channels: [128, 64, 64]
      aggregation:
        _target_: sharpf.modeling.AggregationMax
  decoder_blocks:
    - _target_: sharpf.modeling.PointOpBlock
      in_features: [0, 1, 2]
      feature_extractor:
        _target_: sharpf.modeling.StackedConv
        channels: [192, 1024]
      aggregation:
        _target_: sharpf.modeling.GlobalMaxPooling
    - _target_: sharpf.modeling.PointOpBlock
      in_features: [0, 1, 2]
      feature_extractor:
        _target_: sharpf.modeling.StackedConv
        channels: [1216, 512, 256]
        dropout_prob: 0.0
    - _target_: sharpf.modeling.PointOpBlock
      feature_extractor:
        _target_: sharpf.modeling.StackedConv
        channels:
          - 256
          - ${logits:${model.model_class.discretization},${model.model_class.margin}}
        bn: false
        relu: false
        conv_bias: true