# @package _group_
model_name: PixelRegressor
params:
  feature_extractor:
    _target_: sharpf.modeling.Unet
    encoder_name: resnet50
    decoder_use_batchnorm: true
    decoder_channels: [256, 128, 64, 32, 16]
    decoder_attention_type: null
    in_channels: 1
  regression_head:
    - _target_: torch.nn.Dropout
      p: 0.5
      inplace: True
    - _target_: torch.nn.Conv2d
      in_channels: 16
      out_channels: 1
      kernel_size: 3
      padding: 1
    - _target_: torch.nn.Sigmoid