# @package _group_

in_channels: 1
out_channels: 250

example_input_array:
  _target_: torch.rand
  size:
    - 1
    - ${model.in_channels}
    - 64
    - 64

output_elements:
  - key: distances
    channel_range:
      - 0
      - 244
  - key: normals
    channel_range:
      - 244
      - 247
  - key: directions
    channel_range:
      - 247
      - 250

model_class:
  _target_: sharpf.modeling.PixelRegressorHist
  a: 0.0
  b: 1.0
  discretization: 240
  margin: 2
  feature_extractor:
    _target_: sharpf.modeling.Unet2D
    encoder_name: resnet50
    decoder_channels: [512, 256, 128, 64]
    decoder_layers: [2, 2, 2, 2]
    in_channels: ${model.in_channels}
    avg_down: true
    act_layer: torch.nn.LeakyReLU
  regression_head:
    _target_: sharpf.modeling.Sequential
    modules:
      - _target_: torch.nn.Dropout
        p: 0.0
      - _target_: torch.nn.Conv2d
        in_channels: 64
        out_channels: ${model.out_channels}
        kernel_size: 3
        padding: 1