# @package _group_

train:
  - _target_: sharpf.utils.abc_utils.torch.TypeCast

val:
  - _target_: sharpf.utils.abc_utils.torch.TypeCast

test:
  - _target_: sharpf.utils.abc_utils.torch.TypeCast

normalisation:
  - data: ['standartize', 'quantile']


