# @package _group_

train:
  - _target_: sharpf.utils.abc_utils.torch.TypeCast
  - _target_: sharpf.utils.abc_utils.torch.Center
  - _target_: sharpf.utils.abc_utils.torch.NormalizeL2
  - _target_: sharpf.utils.abc_utils.torch.Random3DRotation

val:
  - _target_: sharpf.utils.abc_utils.torch.TypeCast
  - _target_: sharpf.utils.abc_utils.torch.Center
  - _target_: sharpf.utils.abc_utils.torch.NormalizeL2

test:
  - _target_: sharpf.utils.abc_utils.torch.TypeCast
  - _target_: sharpf.utils.abc_utils.torch.Center
  - _target_: sharpf.utils.abc_utils.torch.NormalizeL2