# @package _group_

in_channels: 1
out_channels: 1

example_input_array:
  _target_: torch.rand
  size:
    - 1
    - ${model.in_channels}
    - 64
    - 64

output_elements:
  - key: preds_sharp
    channel_range:
      - 0
      - ${model.out_channels}

model_class:
  _target_: defs.modeling.PixelSegmentator
  feature_extractor:
    _target_: defs.modeling.Unet2D
    encoder_name: resnet152
    decoder_channels: [512, 256, 128, 64]
    decoder_layers: [2, 2, 2, 2]
    in_channels: ${model.in_channels}
    avg_down: false
    act_layer: torch.nn.ReLU
  #    base_width: 66
  segmentation_head:
    _target_: defs.modeling.Sequential
    modules:
      - _target_: torch.nn.Dropout
        p: 0.0
      - _target_: torch.nn.Conv2d
        in_channels: 64
        out_channels: ${model.out_channels}
        kernel_size: 3
        padding: 1