# @package _group_

pl_class:
  _target_: sharpf.modeling.SharpFeaturesRegressionTask

directions_lambda: 1.0

losses:
  - name: distances_loss
    out_key: distances
    gt_key: distances
    lambda: 1.0
    loss_func:
      _target_: sharpf.modeling.kl_div_loss
      a: ${model.model_class.a}
      b: ${model.model_class.b}
      discretization: ${model.model_class.discretization}
      margin: ${model.model_class.margin}
  - name: directions_loss
    out_key: directions
    gt_key: directions
    lambda: ${task.directions_lambda}
    loss_func:
      _target_: torch.nn.functional.mse_loss

checkpoint_on: mean_rmse/val
early_stop:
  value: ${task.checkpoint_on}
  mode: min
  min_delta: 0.001
  patience: 10
