defaults:
  - callbacks: ???
  - dataloader: standard
  - datasets: ???
  - loggers: test_tube
  - model: ???
  - transform: ???
  - system: ???
  - trainer: project
  - scheduler: exponential09
  - opt: adam

eval_only: false

# if eval_only = true: test_weights must be the absolute path to weights
# otherwise use `null` if you want to use the last checkpoint after training or `best` to choose the checkpoint
# performing best on the validation set
test_weights: best

preload_weights: ~  # path to ckpt to preload weights from before training