defaults:
  - data: abc-pc
  - model: dgcnn-4k
  - transforms: pc-basic
  - meta_arch: point-sharpness-regressor
  - trainer: trainer
  - scheduler: step
  - opt: adam

data_loader:
  train:
    total_batch_size: 32
    num_workers: 3  # depending on RAM capacity set this value carefully
    pin_memory: true
  val:
    total_batch_size: 32
    num_workers: 3  # depending on RAM capacity set this value carefully
    pin_memory: true
  test:
    total_batch_size: 32
    num_workers: 3 # depending on RAM capacity set this value carefully
    pin_memory: true

eval_only: false

# if eval_only = true: test_wights must be the absolute path to weights
# otherwise use `null` if you want to use the last checkpoint after training or `best` to choose the checkpoint
# performing best on the validation set
test_weights: best

seed: 123