defaults:
  - data: abc-pointcloud
  - model: dgcnn-4k
  - transforms: pc-basic
  - meta_arch: point-sharpness-regressor
  - trainer: trainer
  - scheduler: step
  - opt: adam

data_loader:
  train:
    total_batch_size: 16
    num_workers: 2
  val:
    total_batch_size: 16
    num_workers: 2
  test:
    total_batch_size: 16
    num_workers: 2

eval_only: false
weights: null
seed: 123
