# @package _group_
model_name: DGCNN
params:
  encoder_blocks:
    - "0":
      in_features: null
      neighbours:
        target: sharpf.modeling.NeighbourKNN
        params:
          k: 30
      local_transform:
        target: sharpf.modeling.LocalDynamicGraph
      features:
        target: sharpf.modeling.StackedConv
        params:
          channels: [6, 64, 64]
          blocks: 2
      aggregation:
        target: sharpf.modeling.AggregationMax
        params:
          dim: -1
          keepdim: true
      interpolation:
        target: torch.nn.Identity
    - "1":
      in_features: null
      neighbours:
        target: sharpf.modeling.NeighbourKNN
        params:
          k: 30
      local_transform:
        target: sharpf.modeling.LocalDynamicGraph
      features:
        target: sharpf.modeling.StackedConv
        params:
          channels: [128, 64, 64]
          blocks: 2
      aggregation:
        target: sharpf.modeling.AggregationMax
        params:
          dim: -1
          keepdim: true
      interpolation:
        target: torch.nn.Identity
    - "2":
      in_features: null
      neighbours:
        target: sharpf.modeling.NeighbourKNN
        params:
          k: 30
      local_transform:
        target: sharpf.modeling.LocalDynamicGraph
      features:
        target: sharpf.modeling.StackedConv
        params:
          channels: [128, 64, 64]
          blocks: 2
      aggregation:
        target: sharpf.modeling.AggregationMax
        params:
          dim: -1
          keepdim: true
      interpolation:
        target: torch.nn.Identity
  decoder_blocks:
    - "0":
      in_features: [0, 1, 2]
      neighbours:
        target: torch.nn.Identity
      local_transform:
        target: torch.nn.Identity
      features:
        target: sharpf.modeling.StackedConv
        params:
          channels: [192, 4096]
          blocks: 1
      aggregation:
        target: sharpf.modeling.AggregationMaxPooling
        params:
          kernel_size: [4096, 1]
          repeat_times: 4096
      interpolation:
        target: torch.nn.Identity
    - "1":
      in_features: [0, 1, 2]
      neighbours:
        target: torch.nn.Identity
      local_transform:
        target: torch.nn.Identity
      features:
        target: sharpf.modeling.StackedConv
        params:
          channels: [4288, 512, 256]
          blocks: 2
          dropout_prob: 0.5
      aggregation:
        target: torch.nn.Identity
      interpolation:
        target: torch.nn.Identity
    - "2":
      in_features: null
      neighbours:
        target: torch.nn.Identity
      local_transform:
        target: torch.nn.Identity
      features:
        target: sharpf.modeling.StackedConv
        params:
          channels: [256, 1]
          blocks: 1
          bn: false
          relu: false
          conv_bias: true
      aggregation:
        target: torch.nn.Identity
      interpolation:
        target: torch.nn.Identity
