# @package _group_

train:
  - dataset_name: train
    dataset_class:
      _target_: sharpf.utils.abc_utils.LotsOfHdf5Files
      io:
        _target_: sharpf.data.PointCloudIO
      data_dir: /trinity/home/r.rakhimov/sharp_features/data/abc/points/high/64k # fixme make user agnostic
      data_label: points
      target_label: distances
      partition: train
      transform: ${transform.train}
      max_loaded_files: 5
val:
  - dataset_name: val
    dataset_class:
      _target_: sharpf.utils.abc_utils.LotsOfHdf5Files
      io:
        _target_: sharpf.data.PointCloudIO
      data_dir: /trinity/home/r.rakhimov/sharp_features/data/abc/points/high/64k
      data_label: points
      target_label: distances
      partition: val
      transform: ${transform.val}
      max_loaded_files: 5
    evaluators: ${evaluators.val}
test:
  - dataset_name: test
    dataset_class:
      _target_: sharpf.utils.abc_utils.LotsOfHdf5Files
      io:
        _target_: sharpf.data.PointCloudIO
      data_dir: /trinity/home/r.rakhimov/sharp_features/data/abc/points/high/64k
      data_label: points
      target_label: distances
      partition: val
      transform: ${transform.test}
      max_loaded_files: 5
    evaluators: ${evaluators.test}
