# @package _group_

resolution: high
noise: 0.0

train:
  - dataset_name: train
    dataset_class:
      _target_: sharpf.utils.abc_utils.LotsOfHdf5Files
      io:
        _target_: sharpf.data.PointCloudIO
      filenames: [
        '/gpfs/gpfs0/3ddl/sharp_features/data_v2_cvpr/points/${datasets.resolution}_res.json/${datasets.noise}/train/train_0.hdf5'
      ]
      labels: ['points', 'distances']
      transform: ${transform.train}
      max_loaded_files: 1
      virtual_size: 65536
val:
  - dataset_name: val
    dataset_class:
      _target_: sharpf.utils.abc_utils.LotsOfHdf5Files
      io:
        _target_: sharpf.data.PointCloudIO
      filenames: [
        '/gpfs/gpfs0/3ddl/sharp_features/data_v2_cvpr/points/${datasets.resolution}_res.json/${datasets.noise}/val/train_0.hdf5',
        '/gpfs/gpfs0/3ddl/sharp_features/data_v2_cvpr/points/${datasets.resolution}_res.json/${datasets.noise}/val/train_1.hdf5'
      ]
      labels: ['points', 'distances']
      transform: ${transform.val}
      max_loaded_files: 2
    evaluators: ${evaluators.val}
test:
  - dataset_name: train
    dataset_class:
      _target_: sharpf.utils.abc_utils.LotsOfHdf5Files
      io:
        _target_: sharpf.data.PointCloudIO
      filenames: [
        '/gpfs/gpfs0/3ddl/sharp_features/data_v2_cvpr/points/${datasets.resolution}_res.json/${datasets.noise}/train/train_0.hdf5'
      ]
      labels: ${datasets.test_labels}
      transform: ${transform.test}
      max_loaded_files: 1
      return_index: true
    evaluators: ${evaluators.test_se}
  - dataset_name: val
    dataset_class:
      _target_: sharpf.utils.abc_utils.LotsOfHdf5Files
      io:
        _target_: sharpf.data.PointCloudIO
      filenames: [
        '/gpfs/gpfs0/3ddl/sharp_features/data_v2_cvpr/points/${datasets.resolution}_res.json/${datasets.noise}/val/train_0.hdf5',
        '/gpfs/gpfs0/3ddl/sharp_features/data_v2_cvpr/points/${datasets.resolution}_res.json/${datasets.noise}/val/train_1.hdf5'
      ]
      labels: ${datasets.test_labels}
      transform: ${transform.test}
      max_loaded_files: 2
      return_index: true
    evaluators: ${evaluators.test_se_vis_save}
  - dataset_name: test
    dataset_class:
      _target_: sharpf.utils.abc_utils.LotsOfHdf5Files
      io:
        _target_: sharpf.data.PointCloudIO
      filenames: [
        '/gpfs/gpfs0/3ddl/sharp_features/data_v2_cvpr/points/${datasets.resolution}_res.json/0.0/test/train_0.hdf5',
        '/gpfs/gpfs0/3ddl/sharp_features/data_v2_cvpr/points/${datasets.resolution}_res.json/0.0/test/train_1.hdf5'
      ]
      labels: ${datasets.test_labels}
      transform: ${transform.test}
      max_loaded_files: 2
      return_index: true
    evaluators: ${evaluators.test_se_vis_save}

test_labels:
  - 'points'
  - 'distances'
  - 'item_id'
  - 'has_sharp'
  - 'has_smell_coarse_surfaces_by_num_faces'
  - 'has_smell_deviating_resolution'
  - 'has_smell_sharpness_discontinuities'
  - 'has_smell_bad_face_sampling'
  - 'has_smell_mismatching_surface_annotation'
  - 'has_smell_coarse_surfaces_by_angles'