# @package _group_

train:
  - dataset_name: train
    dataset_class:
      _target_: sharpf.utils.abc_utils.LotsOfHdf5Files
      io:
        _target_: sharpf.data.DepthMapIO
      filenames: [
        '/gpfs/gpfs0/3ddl/sharp_features/data_v2_cvpr/images/high_res.json/0.0/test/train_0.hdf5'
      ]
      labels: ['image', 'distances']
      transform: ${transform.train}
      max_loaded_files: 6
val:
  - dataset_name: val
    dataset_class:
      _target_: sharpf.utils.abc_utils.LotsOfHdf5Files
      io:
       _target_: sharpf.data.DepthMapIO
      filenames: [
        '/gpfs/gpfs0/3ddl/sharp_features/data_v2_cvpr/images/high_res.json/0.0/test/train_0.hdf5',
        '/gpfs/gpfs0/3ddl/sharp_features/data_v2_cvpr/images/high_res.json/0.0/test/train_1.hdf5',
        '/gpfs/gpfs0/3ddl/sharp_features/data_v2_cvpr/images/high_res.json/0.0/test/train_2.hdf5'
      ]
      labels: ['image', 'distances', 'item_id', 'camera_pose']
      transform: ${transform.val}
      max_loaded_files: 1
      return_index: True
    evaluators: ${evaluators.val}
test:
  - dataset_name: test
    dataset_class:
      _target_: sharpf.utils.abc_utils.LotsOfHdf5Files
      io:
        _target_: sharpf.data.DepthMapIO
      filenames: [
        '/gpfs/gpfs0/3ddl/sharp_features/data_v2_cvpr/images/high_res.json/0.0/test/train_0.hdf5',
        '/gpfs/gpfs0/3ddl/sharp_features/data_v2_cvpr/images/high_res.json/0.0/test/train_1.hdf5',
        '/gpfs/gpfs0/3ddl/sharp_features/data_v2_cvpr/images/high_res.json/0.0/test/train_2.hdf5'
      ]
      labels: ['image', 'distances', 'item_id', 'camera_pose']
      transform: ${transform.test}
      max_loaded_files: 1
      return_index: True
    evaluators: ${evaluators.test}
