# @package _group_

resolution: high
resolution_q: 0.02
noise: 0.0

train:
  - dataset_name: train
    dataset_class:
      _target_: defs.utils.abc_utils.LotsOfHdf5Files
      io:
        _target_: defs.data.PointCloudIO
      filenames: [
        '${hydra:runtime.cwd}/data/points/${datasets.resolution}_res.json/${datasets.noise}/train_w_v/train_0.hdf5',
        '${hydra:runtime.cwd}/data/points/${datasets.resolution}_res.json/${datasets.noise}/train_w_v/train_1.hdf5',
        '${hydra:runtime.cwd}/data/points/${datasets.resolution}_res.json/${datasets.noise}/train_w_v/train_2.hdf5',
        '${hydra:runtime.cwd}/data/points/${datasets.resolution}_res.json/${datasets.noise}/train_w_v/train_3.hdf5'
      ]
      labels: ['points', 'distances', 'voronoi']
      transform: ${transform.train}
      max_loaded_files: 4
val:
  - dataset_name: val
    dataset_class:
      _target_: defs.utils.abc_utils.LotsOfHdf5Files
      io:
        _target_: defs.data.PointCloudIO
      filenames: [
        '${hydra:runtime.cwd}/data/points/${datasets.resolution}_res.json/${datasets.noise}/val_w_v/train_0.hdf5',
        '${hydra:runtime.cwd}/data/points/${datasets.resolution}_res.json/${datasets.noise}/val_w_v/train_1.hdf5'
      ]
      labels: ['points', 'distances', 'voronoi']
      transform: ${transform.val}
      max_loaded_files: 2
test:
  #  - dataset_name: train
  #    dataset_class:
  #      _target_: defs.utils.abc_utils.LotsOfHdf5Files
  #      io:
  #        _target_: defs.data.PointCloudIO
  #      filenames: [
  #        '${hydra:runtime.cwd}/data/points/${datasets.resolution}_res.json/${datasets.noise}/train_w_v/train_0.hdf5',
  #        '${hydra:runtime.cwd}/data/points/${datasets.resolution}_res.json/${datasets.noise}/train_w_v/train_1.hdf5',
  #        '${hydra:runtime.cwd}/data/points/${datasets.resolution}_res.json/${datasets.noise}/train_w_v/train_2.hdf5',
  #        '${hydra:runtime.cwd}/data/points/${datasets.resolution}_res.json/${datasets.noise}/train_w_v/train_3.hdf5'
  #      ]
  #      labels: ['points', 'distances', 'voronoi']
  #      transform: ${transform.test}
  #      max_loaded_files: 4
  #      return_index: true
  #  - dataset_name: val
  #    dataset_class:
  #      _target_: defs.utils.abc_utils.LotsOfHdf5Files
  #      io:
  #        _target_: defs.data.PointCloudIO
  #      filenames: [
  #        '${hydra:runtime.cwd}/data/points/${datasets.resolution}_res.json/${datasets.noise}/val_w_v/train_0.hdf5',
  #        '${hydra:runtime.cwd}/data/points/${datasets.resolution}_res.json/${datasets.noise}/val_w_v/train_1.hdf5'
  #      ]
  #      labels: ['points', 'distances', 'voronoi']
  #      transform: ${transform.test}
  #      max_loaded_files: 2
  #      return_index: true
  - dataset_name: test
    dataset_class:
      _target_: defs.utils.abc_utils.LotsOfHdf5Files
      io:
        _target_: defs.data.PointCloudIO
      filenames: [
        '${hydra:runtime.cwd}/data/points/${datasets.resolution}_res.json/0.0/test_w_v/train_0.hdf5',
        '${hydra:runtime.cwd}/data/points/${datasets.resolution}_res.json/0.0/test_w_v/train_1.hdf5'
      ]
      labels: ['points', 'distances', 'voronoi']
      transform: ${transform.test}
      max_loaded_files: 2
      return_index: true