# @package _group_

resolution_q: 0.25
compute_metrics: true
save_predictions: false

train:
  - dataset_name: train
    dataset_class:
      _target_: defs.utils.abc_utils.LotsOfHdf5Files
      io:
        _target_: defs.data.AnnotatedViewIO
      data_dir: '/gpfs/gpfs0/3ddl/sharp_features/data_rw_iccv/images_whole/train'
      labels: ['points', 'distances']
      transform: ${transform.train}
      max_loaded_files: 10000
      preload: true
val:
  - dataset_name: val
    dataset_class:
      _target_: defs.utils.abc_utils.LotsOfHdf5Files
      io:
        _target_: defs.data.AnnotatedViewIO
      data_dir: '/gpfs/gpfs0/3ddl/sharp_features/data_rw_iccv/images_whole/val'
      labels: ['points', 'distances']
      transform: ${transform.val}
      max_loaded_files: 10000
      return_index: true
      preload: true
test:
  - dataset_name: val
    dataset_class:
      _target_: defs.utils.abc_utils.LotsOfHdf5Files
      io:
        _target_: defs.data.AnnotatedViewIO
      data_dir: '/gpfs/gpfs0/3ddl/sharp_features/data_rw_iccv/images_whole/val'
      labels: ['points', 'distances']
      transform: ${transform.test}
      max_loaded_files: 10000
      return_index: true
      preload: true
  - dataset_name: test
    dataset_class:
      _target_: defs.utils.abc_utils.LotsOfHdf5Files
      io:
        _target_: defs.data.AnnotatedViewIO
      data_dir: '/gpfs/gpfs0/3ddl/sharp_features/data_rw_iccv/images_whole/test'
      labels: ['points', 'distances']
      transform: ${transform.test}
      max_loaded_files: 10000
      return_index: true
      preload: true