# @package _group_

path: ~

train: ~
val: ~
test:
  - dataset_name: test
    dataset_class:
      _target_: sharpf.utils.abc_utils.LotsOfHdf5Files
      io:
        _target_: sharpf.data.PointCloudIO
      filenames: ['${datasets.path}']
      labels: ${datasets.test_labels}
      transform: ${transform.test}
      max_loaded_files: 1
      return_index: true
    evaluators: ${evaluators.test_whole}

test_labels:
  - 'points'
  - 'distances'
  - 'item_id'
  - 'has_sharp'
  - 'has_smell_coarse_surfaces_by_num_faces'
  - 'has_smell_deviating_resolution'
  - 'has_smell_sharpness_discontinuities'
  - 'has_smell_bad_face_sampling'
  - 'has_smell_mismatching_surface_annotation'
  - 'has_smell_coarse_surfaces_by_angles'