# @package _group_

target: sharpf.modeling.DepthSegmentator
monitor: val_balanced_accuracy #TODO: add balanced accuracy metric class
loss:
   target: torch.nn.functional.binary_cross_entropy_with_logits
